apiVersion: v1
kind: Pod
metadata:
  name: api-9dc475b7d-hhspq
  generateName: api-9dc475b7d-
  namespace: magicbox
  uid: 2bb055f9-4f41-4f2e-b2b2-b80649cacd74
  resourceVersion: '27154008'
  creationTimestamp: '2023-03-01T08:47:19Z'
  labels:
    app: api
    pod-template-hash: 9dc475b7d
  ownerReferences:
    - apiVersion: apps/v1
      kind: ReplicaSet
      name: api-9dc475b7d
      uid: 42ec726b-f447-4258-a28a-3672f279cb1e
      controller: true
      blockOwnerDeletion: true
  managedFields:
    - manager: kube-controller-manager
      operation: Update
      apiVersion: v1
      time: '2023-03-01T08:47:19Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:generateName: {}
          f:labels:
            .: {}
            f:app: {}
            f:pod-template-hash: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"42ec726b-f447-4258-a28a-3672f279cb1e"}: {}
        f:spec:
          f:containers:
            k:{"name":"api"}:
              .: {}
              f:env:
                .: {}
                k:{"name":"ACCESS_TOKEN_EXPIRES_IN"}:
                  .: {}
                  f:name: {}
                  f:value: {}
                k:{"name":"API_PORT"}:
                  .: {}
                  f:name: {}
                  f:value: {}
                k:{"name":"API_PREFIX"}:
                  .: {}
                  f:name: {}
                  f:value: {}
                k:{"name":"EXCHAPPID"}:
                  .: {}
                  f:name: {}
                  f:value: {}
                k:{"name":"EXCHCERTIFICATE"}:
                  .: {}
                  f:name: {}
                  f:value: {}
                k:{"name":"EXCHORGANIZATION"}:
                  .: {}
                  f:name: {}
                  f:value: {}
                k:{"name":"MONGO_DB"}:
                  .: {}
                  f:name: {}
                  f:value: {}
                k:{"name":"MONGO_SERVER"}:
                  .: {}
                  f:name: {}
                  f:value: {}
                k:{"name":"REFRESH_TOKEN_EXPIRES_IN"}:
                  .: {}
                  f:name: {}
                  f:value: {}
                k:{"name":"TOKEN_SECRET"}:
                  .: {}
                  f:name: {}
                  f:value: {}
                k:{"name":"TOKEN_TYPE"}:
                  .: {}
                  f:name: {}
                  f:value: {}
              f:image: {}
              f:imagePullPolicy: {}
              f:name: {}
              f:ports:
                .: {}
                k:{"containerPort":3000,"protocol":"TCP"}:
                  .: {}
                  f:containerPort: {}
                  f:name: {}
                  f:protocol: {}
              f:resources: {}
              f:terminationMessagePath: {}
              f:terminationMessagePolicy: {}
          f:dnsPolicy: {}
          f:enableServiceLinks: {}
          f:restartPolicy: {}
          f:schedulerName: {}
          f:securityContext: {}
          f:terminationGracePeriodSeconds: {}
    - manager: kubelet
      operation: Update
      apiVersion: v1
      time: '2023-03-01T08:48:03Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:conditions:
            k:{"type":"ContainersReady"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:status: {}
              f:type: {}
            k:{"type":"Initialized"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:status: {}
              f:type: {}
            k:{"type":"Ready"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:status: {}
              f:type: {}
          f:containerStatuses: {}
          f:hostIP: {}
          f:phase: {}
          f:podIP: {}
          f:podIPs:
            .: {}
            k:{"ip":"10.244.1.27"}:
              .: {}
              f:ip: {}
          f:startTime: {}
      subresource: status
  selfLink: /api/v1/namespaces/magicbox/pods/api-9dc475b7d-hhspq
status:
  phase: Running
  conditions:
    - type: Initialized
      status: 'True'
      
      lastTransitionTime: '2023-03-01T08:47:19Z'
    - type: Ready
      status: 'True'
    
      lastTransitionTime: '2023-03-01T08:48:03Z'
    - type: ContainersReady
      status: 'True'
      
      lastTransitionTime: '2023-03-01T08:48:03Z'
    - type: PodScheduled
      status: 'True'
      
      lastTransitionTime: '2023-03-01T08:47:19Z'
  hostIP: 10.224.0.4
  podIP: 10.244.1.27
  podIPs:
    - ip: 10.244.1.27
  startTime: '2023-03-01T08:47:19Z'
  containerStatuses:
    - name: api
      state:
        running:
          startedAt: '2023-03-01T08:48:02Z'
      lastState: {}
      ready: true
      restartCount: 0
      image: nexiintra365.azurecr.io/magic.api:v20230301a
      imageID: >-
        nexiintra365.azurecr.io/magic.api@sha256:2cc9d9e620f2ac67aae0f120852509112d8c332ad7ed60ff16dcdf7efeae6f8e
      containerID: >-
        containerd://3f1e98851a8d62847c8d69e339d2d9f97146adbcb747980001ac3b8c4b08c0c1
      started: true
  qosClass: BestEffort
spec:
  volumes:
    - name: kube-api-access-tvg65
      projected:
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              name: kube-root-ca.crt
              items:
                - key: ca.crt
                  path: ca.crt
          - downwardAPI:
              items:
                - path: namespace
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
        defaultMode: 420
  containers:
    - name: api
      image: nexiintra365.azurecr.io/magic.api:v20230301a
      ports:
        - name: http-port
          containerPort: 3000
          protocol: TCP
      env:
        - name: API_PORT
          value: '3000'
        - name: API_PREFIX
          value: /api
        - name: MONGO_SERVER
          value: >-
            mongodb://root:SZG18brNu2@mongo-magicbox-mongodb:27017/?authMechanism=DEFAULT
        - name: MONGO_DB
          value: M365x65867376
        - name: EXCHAPPID
          value: a8594053-1bf1-490e-bba9-ae08e0f36bcd
        - name: EXCHORGANIZATION
          value: M365x65867376.onmicrosoft.com
        - name: EXCHCERTIFICATE
          value: >-
            MIIJKwIBAzCCCOcGCSqGSIb3DQEHAaCCCNgEggjUMIII0DCCBTkGCSqGSIb3DQEHAaCCBSoEggUmMIIFIjCCBR4GCyqGSIb3DQEMCgECoIIE9jCCBPIwJAYKKoZIhvcNAQwBAzAWBBCt6s4KPQ776pp8T4l/vaAkAgIH0ASCBMgbUR7XeyvXkMxkJi2/gEYOAg0kXuD4lvkcN9f8t6JLN+UbV/hwyHtHcZwxIGH867E0p0Q9MtnvQe5yHYBqPcFt/ZRwczN6t2DZvplC23jFBhrRiXS1c8j3NOzsBNptsilmn59QzY3kVBtQkGGQAI1EJyXZbS/ApPBa/6rRDMt5N9YdUqd1SOcrBBS6t3JoJ/qZQde+DmG71WBLPwanXvR/eUHh3FB2LoSv1zg392/r23jcfbqOdrE9kT+OW1b78GrfcEc9Z+Vx7Ar+9oK7EBUdV7QfbVbWaisn11+Wq+CGwTG82OJzWMcJmYKKqQTJkMr3tycc7jVPgaeK3PAu8zvB+0rYq5nonB7ss07ZUwjsvfQWz/AwociatjV+P7/aCzt3zJ/giskiQbMkNOf9vsJN1OfTAYegojxXYWcqCUFQev5gDfAr973K0nOPXfxoitgdi0dmJYrkav/OVtDFj78k80F1OWvXKAdeRt4wtyaKiglDX4b2uqZKU7kPflknvrIEPQ8xQTfF0vf8EST5ZTupK0oijX1mNWHm1imt++KT57tBYpXgm1ZPCsNl6RpffvG/OO+GAL3swIeoa8hclH4cI+5pUtSL3/NWC6f18DQpA06LyDR1ypsyaF5fPt+gfTJFbiiXvwfPTOd/7ju6/6odqier3W6yR0j4sqLqOn+ZIuzgJD5JCvhU5C4HxvU4bSvIOx67xUtoaCnOVfvtvHAIC1xS9P5WBD6Ur3wphIaDtDaa/jPG0qPS0HiQYWODgnqHc/wAiOtvHFmoFX4r13mkwxIjPhAKUm1L/47X87Vp+WgVOKmGuO55m7BkmxRCpGcyfcssaQzuIB+YB07U4xYX2Yg0YdP4rbGqBKK6AjLN/Amb9EDHsl/LclFU46c38hyW492fGP0L3ILBFzWCkZ5sP5JaQOhRipCCC+Sosh8SVK3/AeGYOAYAWp8G1sUoe1Cc7vkRBbSM2hkiU+HepuI9aCJZC61jlmvnQf25bOuNiHvqHqXb/FNcpfwzabWV7EOhYACti3EhqrZml6AbkT2PBu2lCyRTgWr4mI7qeD2CrbyAkjB4Pz2G3I+BUnQR63m7s/3qWSZ35b/5flSewqtSWV3LvS3rO5/x9zNdzDWXKjbf15hFohZ+KLJa6njl7VyAHsHs2f4BUCqBoMXjJheUlpSOhD9A8n8nSZp6O9yfIHiHYUiIwYrCLI9+rll/VJ1w8sU/f0haSa/9aKa5iXPYXJWe2YwNCnFqWgKcmwZsPP3roxR8blQRjdoEwCCc1b9oSiJVRZ9l12I9fwLgjcEmjmT/3vJSja2oIMrQ5nIdUqQD1C9s3XQAGeSVUi3RWespCCooNLvq8QG1TIuNCh+CMOyApOyufPe6gNrDQr+ux3N68y4judmO2KKWMJMNdFmtGgeezQ+TZl+GUE82cfcCzRoYN82F9aVVOJngf/gyzGxDpuj6uo/btIoUZbuYbWauLrWi75zAJXJEafHhL0j45wuVsoIThYCTDBZNswlEu21OANlHLmM02mSvhWuDd5PMlyF1+tqGzBtXksA5GyWhJBWlZg4czdvBusxN98D+1ouaMtx82Hj+gi+Odlg+1j6AcCuAQ6lL8LnzjjvDDNr+OyeICq1fR/gxFTATBgkqhkiG9w0BCRUxBgQEAAAAADCCA48GCSqGSIb3DQEHBqCCA4AwggN8AgEAMIIDdQYJKoZIhvcNAQcBMCQGCiqGSIb3DQEMAQMwFgQQIibFragiArTLZeQOG6gCTgICB9CAggNAMGv99tJqARKQ5Mfk6MmZuLQOtZII9eyEkaf/OrKLq2WxaeXUN4zr4Vnk8EOI0Clrk2VMQsA1KfiRHZw6TveeMiTO383gVAOgmTfmkydK0l4gK6yR62zQuVxgF/lCsj7p5G80CfvqzcIrXaYi+IO2pipdJ9u/USGcfLjgckSEl7fQQbDiKNer7T2nvycoiOZO/jSf+2mHVGm80L+v9wiAEVi0EG2wN64GFygx62VLmzfnpMcnqu4RUobT2pZY2hxLw1kPu5w+24MhLZuN9rFr+e6CXCOq5Em0jtgCvM8rxMuJJ7xxi5dF7ZDtyuwOwcescWUBvaf78wpsgcNxmuc0H9sZTTEPpm0iFJ65x+9PIbiF9+o2IGLMKuv8yGKGGbbhw3Cn3l4T99LnpIpoIHtZEFb9gZg9idRPAGxzqXxQfSxDU69mbiBBYS3zBxsaUZU1Zm/ydqsMMY5BpaFqD5gV6Nb3Y3hB4lUQnfYJbRiWtJ88/9FyOXu53KH1CEdCK+gQMCxqiwDpEuRF8GTVjmoySde7i3dY3+cDLgvhHLLQKsTe1blsx7p13gZ5cQ6WTkmiU1KjOOvvIAfp0dWLHetMy/NCRo3NnXuFmsmPpi1+6nzabTgtiLSTm4tQU5Kqc0U77oNIe6DfYUJ2S1ybEbOkVdprMsmn9J/Z9uHVxQZHsBxEpguSjJOo5uDmUV45og4syRyP/u/8KuU9L/JvXfjO4pwYBqa6Mg7h2axsqz8SEONMUdRZK5PBunQxlpbVcb9VpIqj4Ot0SkGWZWaNCy+zWBXfQMmwgd6uDx95JUkhCQnZ/zfgss5saGnQE08JNtHE319lBYponVVNyQjfuURh3RFpwgrqPCfKZ+ABth18rNrNNnHx8LWz9QWGQ0yiujtGkO04r7suUN2Jx+0d41P3hdcpHcOWLYoGy5Rk6mqzcVuAfte/J/smEJgmuSzHYkcWmCqDaPyIYKlZE4ZewFDbpXjDsYhCd7GE1VHL8ID3cg9sEvIF1IjXTFSV/IVZNardmDWBUZkh4iPCEOmk32uBJmiYyINIS58e/0STy3BAhGPn6PVstS4UdFVWLakom5BKosvinzkfoKo5tbeYnePAWDA7MB8wBwYFKw4DAhoEFEthKSj5SlnSiCiD2TQnavFg9fR2BBREyWWI+A9cY2XiXUyzY6F23PyYXgICB9A=
        - name: TOKEN_SECRET
          value: m470k3n
        - name: TOKEN_TYPE
          value: Bearer
        - name: ACCESS_TOKEN_EXPIRES_IN
          value: 1h
        - name: REFRESH_TOKEN_EXPIRES_IN
          value: 2h
      resources: {}
      volumeMounts:
        - name: kube-api-access-tvg65
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  dnsPolicy: ClusterFirst
  serviceAccountName: default
  serviceAccount: default
  nodeName: aks-nodepool1-35651235-vmss000000
  securityContext: {}
  schedulerName: default-scheduler
  tolerations:
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
  priority: 0
  enableServiceLinks: true
  preemptionPolicy: PreemptLowerPriority
